#!/bin/bash

RETURN=0

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "Testing for blog thumbnails"

for POST in _posts/*
do
  if sed -n '/^---$/,/^---$/p' $POST | grep -q "thumbnail[ \t]*:"
  then
    echo -e "[${GREEN} PASS ${NC}] ${POST}"
  else
    echo -e "[${RED} FAIL ${NC}] ${RED}${POST} - no thumbnail set.${NC}"
    let RETURN=1
  fi
done

exit $RETURN
